
# https://fly.io/docs/reference/configuration

app = 'insanely-fast-whisper-api' # Replace with your app name
primary_region = 'sjc'

[build]
image = 'yoeven/insanely-fast-whisper-api:latest'
## Remove the line above to rebuild the image from the Dockerfile

[[mounts]]
source = 'data'
destination = '/root/.cache'
initial_size = '30gb'


[http_service]
internal_port = 9000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'a100-80gb'
memory = '8gb'
cpu_kind = 'performance'
cpus = 4
